version: '3'

services:
  bookings:
    build:
      context: .
      dockerfile: apps/bookings/Dockerfile
      target: development
    container_name: bookings
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    env_file:
      - .env.local
    ports:
      - "3306:3306"